redmine-n8n/redmine/plugins/redmine_ai_helper/config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html
RedmineApp::Application.routes.draw do
  post "projects/:id/ai_helper/chat", to: "ai_helper#chat", as: "ai_helper_chat"
  get "projects/:id/ai_helper/chat_form", to: "ai_helper#chat_form", as: "ai_helper_chat_form"
  get "projects/:id/ai_helper/reload", to: "ai_helper#reload", as: "ai_helper_reload"
  get "projects/:id/ai_helper/clear", to: "ai_helper#clear", as: "ai_helper_clear"
  get "projects/:id/ai_helper/history", to: "ai_helper#history", as: "ai_helper_history"
  get "projects/:id/ai_helper/conversation/:conversation_id", to: "ai_helper#conversation", as: "ai_helper_conversation"
  delete "projects/:id/ai_helper/conversation/:conversation_id", to: "ai_helper#conversation", as: "ai_helper_delete_conversation"
  post "projects/:id/ai_helper/call_llm", to: "ai_helper#call_llm", as: "ai_helper_call_llm"
  get "ai_helper/issue/:id/summary", to: "ai_helper#issue_summary", as: "ai_helper_issue_summary"
  post "ai_helper/issue/:id/generate_summary", to: "ai_helper#generate_issue_summary", as: "ai_helper_generate_issue_summary"
  get "ai_helper/wiki/:id/summary", to: "ai_helper#wiki_summary", as: "ai_helper_wiki_summary"
  post "ai_helper/wiki/:id/generate_summary", to: "ai_helper#generate_wiki_summary", as: "ai_helper_generate_wiki_summary"
  post "ai_helper/issue/:id/generate_reply", to: "ai_helper#generate_issue_reply", as: "ai_helper_generate_issue_reply"
  post "ai_helper/issue/:id/subissue_gen", to: "ai_helper#generate_sub_issues", as: "ai_helper_subissue_gen"
  post "ai_helper/issue/:id/add_sub_issues", to: "ai_helper#add_sub_issues", as: "ai_helper_add_sub_issues"
  get "ai_helper/issue/:id/similar_issues", to: "ai_helper#similar_issues", as: "ai_helper_similar_issues"
  get "projects/:id/ai_helper/project_health", to: "ai_helper#project_health", as: "ai_helper_project_health"
  get "projects/:id/ai_helper/generate_project_health", to: "ai_helper#generate_project_health", as: "ai_helper_generate_project_health"
  post "projects/:id/ai_helper/project_health_pdf", to: "ai_helper#project_health_pdf", as: "ai_helper_project_health_pdf"
  post "projects/:id/ai_helper/project_health_markdown", to: "ai_helper#project_health_markdown", as: "ai_helper_project_health_markdown"

  get "ai_helper_settings/index", to: "ai_helper_settings#index", as: "ai_helper_setting"
  post "ai_helper_settings/index", to: "ai_helper_settings#update", as: "ai_helper_setting_update"

  get "ai_helper_model_profiles", to: "ai_helper_model_profiles#index", as: "ai_helper_model_profiles"
  get "ai_helper_model_profiles/:id", to: "ai_helper_model_profiles#show", as: "ai_helper_model_profiles_show"
  get "ai_helper_model_profiles/:id/edit", to: "ai_helper_model_profiles#edit", as: "ai_helper_model_profiles_edit"
  get "ai_helper_model_profiles_new", to: "ai_helper_model_profiles#new", as: "ai_helper_model_profiles_new"
  post "ai_helper_model_profiles", to: "ai_helper_model_profiles#create", as: "ai_helper_model_profiles_create"
  post "ai_helper_model_profiles/:id/edit", to: "ai_helper_model_profiles#update", as: "ai_helper_model_profiles_update"
  delete "ai_helper_model_profiles/:id", to: "ai_helper_model_profiles#destroy", as: "ai_helper_model_profiles_destroy"

  # get "ai_helper_project_settings/:id", to: "ai_helper_project_settings#show", as: "ai_helper_project_settings"
  patch "projects/:id/ai_helper_project_settings", to: "ai_helper_project_settings#update", as: "ai_helper_project_settings_update"
end

redmine-n8n/redmine/plugins/redmine_ai_helper/app/controllers/ai_helper_controller.rb
# frozen_string_literal: true
# This controller is responsible for handling the chat messages between the user and the AI.
require "redmine_ai_helper/llm"
require "redmine_ai_helper/logger"
require "redmine_ai_helper/export/pdf/project_health_pdf_helper"

class AiHelperController < ApplicationController
  include ActionController::Live
  include RedmineAiHelper::Logger
  include AiHelperHelper
  include RedmineAiHelper::Export::PDF::ProjectHealthPdfHelper

  protect_from_forgery except: [:generate_project_health]
  before_action :find_issue, only: [:issue_summary, :update_issue_summary, :generate_issue_summary, :generate_issue_reply, :generate_sub_issues, :add_sub_issues, :similar_issues]
  before_action :find_wiki_page, only: [:wiki_summary, :generate_wiki_summary]
  before_action :find_project, except: [:issue_summary, :wiki_summary, :generate_issue_summary, :generate_wiki_summary, :generate_issue_reply, :generate_sub_issues, :add_sub_issues, :similar_issues]
  before_action :find_user, :create_session, :find_conversation
  before_action :authorize, except: [:project_health, :generate_project_health]
  before_action :authorize_project_health, only: [:project_health, :generate_project_health]

  # Display the chat form in the sidebar
  def chat_form
    @message = AiHelperMessage.new
    render partial: "ai_helper/chat_form"
  end

  # Redisplay the chat screen
  def reload
    render partial: "ai_helper/chat"
  end

  # Reflect the message entered in the chat form on the chat screen
  def chat
    @message = AiHelperMessage.new
    unless @conversation.id
      @conversation.title = "Chat with AI"
      @conversation.save!
      set_conversation_id(@conversation.id)
    end
    @message.conversation = @conversation
    @message.role = "user"
    @message.content = params[:ai_helper_message][:content]
    @message.save!
    @conversation = AiHelperConversation.find(@conversation.id)
    AiHelperConversation.cleanup_old_conversations
    render partial: "ai_helper/chat"
  end

  # Load the specified conversation
  # If the request is a delete request, delete the conversation
  def conversation
    if request.delete?
      conversation = AiHelperConversation.find(params[:conversation_id])
      need_reload = conversation.id == @conversation.id
      conversation.destroy!
      session[:ai_helper] = {} if need_reload
      return render json: { status: "ok", reload: need_reload }
    end
    @conversation = AiHelperConversation.find(params[:conversation_id])
    set_conversation_id(@conversation.id)
    reload
  end

  # Display the conversation history
  def history
    @conversations = AiHelperConversation.where(user: @user).order(updated_at: :desc).limit(10)
    render partial: "ai_helper/history"
  end

  # Display the issue summary
  def issue_summary
    summary = AiHelperSummaryCache.issue_cache(issue_id: @issue.id)
    if params[:update] == "true" && summary
      summary.destroy!
      summary = nil
    end

    render partial: "ai_helper/issue_summary", locals: { summary: summary }
  end

  # Generate issue summary with streaming
  def generate_issue_summary
    # Clear existing cache
    summary = AiHelperSummaryCache.issue_cache(issue_id: @issue.id)
    summary&.destroy!

    llm = RedmineAiHelper::Llm.new
    full_content = ""

    stream_llm_response do |stream_proc|
      # Wrap stream_proc to capture content for caching
      cache_proc = Proc.new do |content|
        full_content += content if content
        stream_proc.call(content)
      end

      content = llm.issue_summary(issue: @issue, stream_proc: cache_proc)
      # Update cache with final content
      AiHelperSummaryCache.update_issue_cache(issue_id: @issue.id, content: content)
    end
  end

  # Display the wiki summary
  def wiki_summary
    summary = AiHelperSummaryCache.wiki_cache(wiki_page_id: @wiki_page.id)
    if params[:update] == "true" && summary
      summary.destroy!
      summary = nil
    end
    llm = RedmineAiHelper::Llm.new
    unless summary
      content = llm.wiki_summary(wiki_page: @wiki_page)
      summary = AiHelperSummaryCache.update_wiki_cache(wiki_page_id: @wiki_page.id, content: content)
    end

    render partial: "ai_helper/wiki_summary_content", locals: { summary: summary }
  end

  # Generate wiki summary with streaming
  def generate_wiki_summary
    # Clear existing cache
    summary = AiHelperSummaryCache.wiki_cache(wiki_page_id: @wiki_page.id)
    summary&.destroy!

    llm = RedmineAiHelper::Llm.new
    full_content = ""

    stream_llm_response do |stream_proc|
      # Wrap stream_proc to capture content for caching
      cache_proc = Proc.new do |content|
        full_content += content if content
        stream_proc.call(content)
      end

      content = llm.wiki_summary(wiki_page: @wiki_page, stream_proc: cache_proc)
      # Update cache with final content
      AiHelperSummaryCache.update_wiki_cache(wiki_page_id: @wiki_page.id, content: content)
    end
  end

  # Call the LLM and stream the response
  def call_llm
    contoller_name = params[:controller_name]
    action_name = params[:action_name]
    content_id = params[:content_id].to_i unless params[:content_id].blank?
    additional_info = {}
    params[:additional_info].each do |key, value|
      additional_info[key] = value
    end
    llm = RedmineAiHelper::Llm.new
    option = {
      controller_name: contoller_name,
      action_name: action_name,
      content_id: content_id,
      project: @project,
      additional_info: additional_info,
    }

    stream_llm_response do |stream_proc|
      @conversation.messages << llm.chat(@conversation, stream_proc, option)
      @conversation.save!
      AiHelperConversation.cleanup_old_conversations
    end
  end

  # Clear the chat screen
  def clear
    session[:ai_helper] = {}
    find_conversation
    render partial: "ai_helper/chat"
  end

  # Receives a POST message with application/json content to generate an issue reply with streaming
  def generate_issue_reply
    unless request.content_type == "application/json"
      render json: { error: "Unsupported Media Type" }, status: :unsupported_media_type and return
    end

    begin
      data = JSON.parse(request.body.read)
    rescue JSON::ParserError
      render json: { error: "Invalid JSON" }, status: :bad_request and return
    end

    instructions = data["instructions"]
    llm = RedmineAiHelper::Llm.new

    stream_llm_response do |stream_proc|
      llm.generate_issue_reply(issue: @issue, instructions: instructions, stream_proc: stream_proc)
    end
  end

  # Generate sub-issues drafts for the given issue
  def generate_sub_issues
    llm = RedmineAiHelper::Llm.new
    unless request.content_type == "application/json"
      render json: { error: "Unsupported Media Type" }, status: :unsupported_media_type and return
    end

    begin
      data = JSON.parse(request.body.read)
    rescue JSON::ParserError
      render json: { error: "Invalid JSON" }, status: :bad_request and return
    end

    instructions = data["instructions"]
    subissues = llm.generate_sub_issues(issue: @issue, instructions: instructions)

    trackers = @issue.allowed_target_trackers
    trackers = trackers.reject do |tracker|
      @issue.tracker_id != tracker.id && tracker.disabled_core_fields.include?("parent_issue_id")
    end
    trackers_options_for_select = trackers.collect { |t| [t.name, t.id] }

    versions = @issue.assignable_versions || []
    versions_options_for_select = versions.collect { |v| [v.name, v.id] }

    render partial: "ai_helper/subissue_gen/issues", locals: { issue: @issue, subissues: subissues, trackers_options_for_select: trackers_options_for_select, versions_options_for_select: versions_options_for_select }
  end

  # Add sub-issues to the current issue
  def add_sub_issues
    issues_param = params[:sub_issues]
    issues_param.each do |issue_param_array|
      issue_param = issue_param_array[1].permit(:subject, :description, :tracker_id, :check, :fixed_version_id)
      # Skip if the issue_param does not have the :check key or if it is false
      next unless issue_param[:check]
      issue = Issue.new
      issue.author = User.current
      issue.project = @issue.project
      issue.parent_id = @issue.id
      issue.subject = issue_param[:subject]
      issue.description = issue_param[:description]
      issue.tracker_id = issue_param[:tracker_id]
      issue.fixed_version_id = issue_param[:fixed_version_id] unless issue_param[:fixed_version_id].blank?
      # Save the issue and handle errors
      unless issue.save
        # If saving fails, collect error messages and display them using i18n
        flash[:error] = issue.errors.full_messages.join("\n")
        redirect_to issue_path(@issue) and return
      end
    end
    redirect_to issue_path(@issue), notice: l(:notice_sub_issues_added)
  end

  # Find similar issues using LLM and IssueAgent
  def similar_issues
    begin
      llm = RedmineAiHelper::Llm.new
      similar_issues = llm.find_similar_issues(issue: @issue)
      
      render partial: "ai_helper/similar_issues", locals: { similar_issues: similar_issues }
    rescue => e
      ai_helper_logger.error "Similar issues search error: #{e.message}"
      ai_helper_logger.error e.backtrace.join("\n")
      render json: { error: e.message }, status: :internal_server_error
    end
  end

  # Display project health report
  def project_health
    cache_key = "project_health_#{@project.id}_#{params[:version_id]}_#{params[:start_date]}_#{params[:end_date]}"
    @health_report = Rails.cache.fetch(cache_key, expires_in: 1.hour) do
      generate_project_health_report
    end

    respond_to do |format|
      format.html { render partial: "ai_helper/project_health", locals: { health_report: @health_report } }
      format.pdf do
        if @health_report && !@health_report.is_a?(Hash)
          filename = "#{@project.identifier}-health-report-#{Date.current.strftime('%Y%m%d')}.pdf"

redmine-n8n/redmine/plugins/redmine_ai_helper/app/helpers/ai_helper_helper.rb
# frozen_string_literal: true
# AiHelperHelper module for AI Helper plugin
module AiHelperHelper
  include Redmine::WikiFormatting::CommonMark

  # Converts a given Markdown text to HTML using the Markdown pipeline.
  def md_to_html(text)
    text = text.encode("UTF-8", invalid: :replace, undef: :replace, replace: "")
    MarkdownPipeline.call(text)[:output].to_s.html_safe
  end
end

redmine-n8n/redmine/plugins/redmine_ai_helper/app/views/ai_helper/subissue_gen/_index.html.erb
<%= l('ai_helper.generate_sub_issues.instructions') %>:
<div>
<%= text_area_tag "ai_helper_subissues_instructions", "", rows: 4, cols: 60, style: "width: 99%;" %>
</div>


<%= button_to l('ai_helper.generate_sub_issues.generate_draft'), "#", onclick: "aiHelperGenerateSubIssues(#{issue.id}); return false;" %>

<div id="ai-helper-generated-subissues">

</div>

<script>
    function aiHelperGenerateSubIssues(issueId) {
        const container = document.getElementById('ai-helper-generated-subissues');
        container.innerHTML = '<div class="ai-helper-loader"></div>';

        const url = "<%= ai_helper_subissue_gen_path(id: issue) %>"

        fetch(url, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'X-CSRF-Token': document.querySelector('meta[name="csrf-token"]').getAttribute('content')
            },
            body: JSON.stringify({
                instructions: document.getElementById('ai_helper_subissues_instructions').value
            })
        })
        .then(response => response.text())
        .then(html => {
            container.innerHTML = html;
        })
        .catch(error => {
            console.error('Error generating sub issues:', error);
            container.innerHTML = '<p>Error generating sub issues. Please try again later.</p>';
        });
    }
</script>

redmine-n8n/redmine/plugins/redmine_ai_helper/app/views/ai_helper/subissue_gen/_issue_description_bottom.html.erb
<% if @project and @project.module_enabled?(:ai_helper) and User.current.allowed_to?({ controller: :ai_helper, action: :chat_form }, @project) and AiHelperSetting.find_or_create.model_profile and User.current.allowed_to?(:add_issues, @project)%>

<span id="ai-helper-subissuer-generator-menu">
<%= link_to sprite_icon("ai-helper-robot", l('ai_helper.generate_sub_issues.title'), plugin: :redmine_ai_helper), '#', onclick: "showSubissuerGenerator(); return false;", class: "ai-helper-subissuer-generator-button" %> |
</span>

<div id="ai-helper-subissuer-generator-area" display="none">
<%= render partial: 'ai_helper/subissue_gen/index', locals: {issue: @issue} %>
</div>

<script>
    // Function to show the subissuer generator area
    function showSubissuerGenerator() {
        const generatorArea = document.getElementById('ai-helper-subissuer-generator-area');
        if (generatorArea) {
            generatorArea.style.display = generatorArea.style.display === 'none' ? 'block' : 'none';
        }
    }
    // Add span#ai-helper-subissuer-generator-menu as the first child of div#issue_tree > div.contextual
    document.addEventListener('DOMContentLoaded', function() {
        const contextualDiv = document.querySelector('#issue_tree > div.contextual');
        if (contextualDiv) {
            const menuSpan = document.getElementById('ai-helper-subissuer-generator-menu');
            if (menuSpan) {
                // Insert the menuSpan as the first child for i18n support
                contextualDiv.insertBefore(menuSpan, contextualDiv.firstChild);
            }
        }

        const issueTreeDiv = document.getElementById('issue_tree');
        if (issueTreeDiv) {
            const generatorArea = document.getElementById('ai-helper-subissuer-generator-area');
            if (generatorArea) {
                issueTreeDiv.appendChild(generatorArea);
                generatorArea.style.display = 'none';
            }
        }
    });
</script>
<% end %>

redmine-n8n/redmine/plugins/redmine_ai_helper/app/views/ai_helper/subissue_gen/_issues.html.erb
<%= form_tag ai_helper_add_sub_issues_path(id: @issue), method: :post do%>
<table class="ai-helper-sub-issues-table">
    <thead>
        <tr>
            <th></th>
            <th><%= l(:field_tracker) %></th>
            <th><%= l(:field_title) %></th>
            <th><%= l(:field_fixed_version) %></th>
            <th><%= l(:field_description) %></th>
        </tr>
    </thead>
    <tbody>
        <% subissues.each_with_index do |sub_issue, i| %>
        <tr>
            <td><%= check_box_tag "sub_issues[#{i}]check", sub_issue.id, true, id: "sub_issue_#{i}" %></td>
            <td>
                <%= select_tag "sub_issues[#{i}]tracker_id", options_for_select(trackers_options_for_select, sub_issue.tracker_id), :title => @issue.tracker.description, id: "sub_issues_tracker_id_#{i}" %>

            </td>
            <td>
                <span id="ai_helper_sub_issue_subject_<%= i %>">
                    <span><%= sub_issue.subject %></span>
                    <%= link_to sprite_icon('edit'), "#", onclick: "ai_helper.edit_sub_issue_subject(#{i}); return false" %>
                </span>
                <span id="ai_helper_sub_issue_subject_edit_<%= i %>" style="display:none;">
                    <%= text_field_tag "sub_issues[#{i}]subject", sub_issue.subject, size: 40, id: "sub_issues_subject_field_#{i}", onkeydown: "return event.key !== 'Enter'", style: "width: 90%;" %>
                    <%= link_to sprite_icon('save'), "#", onclick: "ai_helper.apply_sub_issue_subject(#{i}); return false" %>
                    <%= link_to sprite_icon('cancel'), "#", onclick: "ai_helper.cancel_sub_issue_subject(#{i}); return false" %>
                </span>
            </td>
            <td>
                <%= select_tag "sub_issues[#{i}]fixed_version_id", options_for_select(versions_options_for_select, issue.fixed_version_id), include_blank: "",id: "sub_issues_fixed_version_id_#{i}" %>

            </td>
            <td>
                <span id="ai_helper_sub_issue_description_<%= i %>">
                    <span><%= sub_issue.description %></span>
                    <%= link_to sprite_icon('edit'), "#", onclick: "ai_helper.edit_sub_issue_description(#{i}); return false" %>
                </span>
                <span id="ai_helper_sub_issue_description_edit_<%= i %>" style="display:none;">
                    <%= text_area_tag "sub_issues[#{i}]description", sub_issue.description, cols: 60, rows: 4, id: "sub_issues_description_field_#{i}", onkeydown: "return event.key !== 'Enter'", style: "width: 90%;" %>
                    <%= link_to sprite_icon('save'), "#", onclick: "ai_helper.apply_sub_issue_description(#{i}); return false" %>
                    <%= link_to sprite_icon('cancel'), "#", onclick: "ai_helper.cancel_sub_issue_description(#{i}); return false" %>
                </span>
            </td>
        </tr>
        <% end %>
    </tbody>

</table>

<%= submit_tag l(:button_add) %>
<% end %>