redmine-n8n/redmine/plugins/redmine_ai_helper/config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html
RedmineApp::Application.routes.draw do
  post "projects/:id/ai_helper/chat", to: "ai_helper#chat", as: "ai_helper_chat"
  get "projects/:id/ai_helper/chat_form", to: "ai_helper#chat_form", as: "ai_helper_chat_form"
  get "projects/:id/ai_helper/reload", to: "ai_helper#reload", as: "ai_helper_reload"
  get "projects/:id/ai_helper/clear", to: "ai_helper#clear", as: "ai_helper_clear"
  get "projects/:id/ai_helper/history", to: "ai_helper#history", as: "ai_helper_history"
  get "projects/:id/ai_helper/conversation/:conversation_id", to: "ai_helper#conversation", as: "ai_helper_conversation"
  delete "projects/:id/ai_helper/conversation/:conversation_id", to: "ai_helper#conversation", as: "ai_helper_delete_conversation"
  post "projects/:id/ai_helper/call_llm", to: "ai_helper#call_llm", as: "ai_helper_call_llm"
  get "ai_helper/issue/:id/summary", to: "ai_helper#issue_summary", as: "ai_helper_issue_summary"
  post "ai_helper/issue/:id/generate_summary", to: "ai_helper#generate_issue_summary", as: "ai_helper_generate_issue_summary"
  get "ai_helper/wiki/:id/summary", to: "ai_helper#wiki_summary", as: "ai_helper_wiki_summary"
  post "ai_helper/wiki/:id/generate_summary", to: "ai_helper#generate_wiki_summary", as: "ai_helper_generate_wiki_summary"
  post "ai_helper/issue/:id/generate_reply", to: "ai_helper#generate_issue_reply", as: "ai_helper_generate_issue_reply"
  post "ai_helper/issue/:id/subissue_gen", to: "ai_helper#generate_sub_issues", as: "ai_helper_subissue_gen"
  post "ai_helper/issue/:id/add_sub_issues", to: "ai_helper#add_sub_issues", as: "ai_helper_add_sub_issues"
  get "ai_helper/issue/:id/similar_issues", to: "ai_helper#similar_issues", as: "ai_helper_similar_issues"
  get "projects/:id/ai_helper/project_health", to: "ai_helper#project_health", as: "ai_helper_project_health"
  get "projects/:id/ai_helper/generate_project_health", to: "ai_helper#generate_project_health", as: "ai_helper_generate_project_health"
  post "projects/:id/ai_helper/project_health_pdf", to: "ai_helper#project_health_pdf", as: "ai_helper_project_health_pdf"
  post "projects/:id/ai_helper/project_health_markdown", to: "ai_helper#project_health_markdown", as: "ai_helper_project_health_markdown"

  get "ai_helper_settings/index", to: "ai_helper_settings#index", as: "ai_helper_setting"
  post "ai_helper_settings/index", to: "ai_helper_settings#update", as: "ai_helper_setting_update"

  get "ai_helper_model_profiles", to: "ai_helper_model_profiles#index", as: "ai_helper_model_profiles"
  get "ai_helper_model_profiles/:id", to: "ai_helper_model_profiles#show", as: "ai_helper_model_profiles_show"
  get "ai_helper_model_profiles/:id/edit", to: "ai_helper_model_profiles#edit", as: "ai_helper_model_profiles_edit"
  get "ai_helper_model_profiles_new", to: "ai_helper_model_profiles#new", as: "ai_helper_model_profiles_new"
  post "ai_helper_model_profiles", to: "ai_helper_model_profiles#create", as: "ai_helper_model_profiles_create"
  post "ai_helper_model_profiles/:id/edit", to: "ai_helper_model_profiles#update", as: "ai_helper_model_profiles_update"
  delete "ai_helper_model_profiles/:id", to: "ai_helper_model_profiles#destroy", as: "ai_helper_model_profiles_destroy"

  # get "ai_helper_project_settings/:id", to: "ai_helper_project_settings#show", as: "ai_helper_project_settings"
  patch "projects/:id/ai_helper_project_settings", to: "ai_helper_project_settings#update", as: "ai_helper_project_settings_update"
end

redmine-n8n/redmine/plugins/redmine_ai_helper/app/models/ai_helper_model_profile.rb
# frozen_string_literal: true
# AiHelperModelProfile model for managing AI Helper model profiles
class AiHelperModelProfile < ApplicationRecord
  include Redmine::SafeAttributes
  validates :name, presence: true, uniqueness: true
  validates :llm_type, presence: true
  validates :access_key, presence: true, if: :access_key_required?
  validates :llm_model, presence: true
  validates :base_uri, presence: true, if: :base_uri_required?
  validates :base_uri, format: { with: URI::regexp(%w[http https]), message: l("ai_helper.model_profiles.messages.must_be_valid_url") }, if: :base_uri_required?
  validates :temperature, presence: true, numericality: { greater_than_or_equal_to: 0.0 }

  safe_attributes "name", "llm_type", "access_key", "organization_id", "base_uri", "version", "llm_model", "temperature", "max_tokens"

  # Replace all characters after the 4th with *
  def masked_access_key
    return access_key if access_key.blank? || access_key.length <= 4
    masked_key = access_key.dup
    masked_key[4..-1] = "*" * (masked_key.length - 4)
    masked_key
  end

  # Returns the String which is displayed in the select box
  def display_name
    "#{name} (#{llm_type}: #{llm_model})"
  end

  # returns true if base_uri is required.
  def base_uri_required?
    # Check if the llm_type is OpenAICompatible
    llm_type == RedmineAiHelper::LlmProvider::LLM_OPENAI_COMPATIBLE ||
      llm_type == RedmineAiHelper::LlmProvider::LLM_AZURE_OPENAI
  end

  # returns true if access_key is required.
  def access_key_required?
    llm_type != RedmineAiHelper::LlmProvider::LLM_OPENAI_COMPATIBLE
  end

  # Returns the LLM type name for display
  def display_llm_type
    names = RedmineAiHelper::LlmProvider.option_for_select
    name = names.find { |n| n[1] == llm_type }
    name ? name[0] : ""
  end
end

redmine-n8n/redmine/plugins/redmine_ai_helper/app/controllers/ai_helper_model_profiles_controller.rb
# frozen_string_literal: true
# Controller for performing CRUD operations on ModelProfile
class AiHelperModelProfilesController < ApplicationController
  layout "admin"
  before_action :require_admin
  before_action :find_model_profile, only: [:show, :edit, :update, :destroy]
  self.main_menu = false

  DUMMY_ACCESS_KEY = "___DUMMY_ACCESS_KEY___"

  # Display the model profile
  def show
    render partial: "ai_helper_model_profiles/show"
  end

  # Display the form for creating a new model profile
  def new
    @title = l("ai_helper.model_profiles.create_profile_title")
    @model_profile = AiHelperModelProfile.new
  end

  # Create a new model profile
  def create
    @model_profile = AiHelperModelProfile.new
    @model_profile.safe_attributes = params[:ai_helper_model_profile]
    if @model_profile.save
      flash[:notice] = l(:notice_successful_create)
      redirect_to ai_helper_setting_path
    else
      render action: :new
    end
  end

  # Display the form for editing an existing model profile
  def edit
  end

  # Update an existing model profile
  def update
    original_access_key = @model_profile.access_key
    @model_profile.safe_attributes = params[:ai_helper_model_profile]
    @model_profile.access_key = original_access_key if @model_profile.access_key == DUMMY_ACCESS_KEY
    if @model_profile.save
      flash[:notice] = l(:notice_successful_update)
      redirect_to ai_helper_setting_path
    else
      render action: :edit
    end
  end

  # Delete an existing model profile
  def destroy
    if @model_profile.destroy
      flash[:notice] = l(:notice_successful_delete)
      redirect_to ai_helper_setting_path
    else
      flash[:error] = l(:error_failed_delete)
      redirect_to ai_helper_setting_path
    end
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  private

  # Find the model profile based on the provided ID
  def find_model_profile
    id = params[:id] # TODO: remove this line
    return if params[:id].blank?
    @model_profile = AiHelperModelProfile.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    render_404
  end
end

redmine-n8n/redmine/plugins/redmine_ai_helper/app/helpers/ai_helper_model_profiles_helper.rb
module AiHelperModelProfilesHelper
end

redmine-n8n/redmine/plugins/redmine_ai_helper/app/views/ai_helper_model_profiles/_form.html.erb
<%= error_messages_for "model_profile" %>
<div class="box tabular">
  <p><%= f.select :llm_type, RedmineAiHelper::LlmProvider.option_for_select %></p>
  <p>
    <%= f.text_field :name, size: 60, required: true, autocomplete: "off" %>
  </p>
  <%
      access_key = ""
      access_key = AiHelperModelProfilesController::DUMMY_ACCESS_KEY unless @model_profile.new_record?
  %>
  <p id="ai-helper-mode-access-key"><%= f.password_field :access_key, value: access_key, size: 60, required: true %></p>
  <p id="ai-helper-model-llm-model">
    <%= f.text_field :llm_model, size: 60, required: true %>
  </p>
  <p id="ai-helper-model-llm-model">
    <%= f.text_field :temperature, size: 60, required: true %>
  </p>
  <p id="ai-helper-model-max-tokens">
    <%= f.text_field :max_tokens, size: 60 %>
  </p>
  <p id="ai-helper-model-organization-id">
    <%= f.text_field :organization_id, size: 60 %>
  </p>
  <p id="ai-helper-model-base-uri">
    <%= f.text_field :base_uri, size: 90, required: true %>
  </p>


</div>

<script>
  document.addEventListener('DOMContentLoaded', function() {
    // LLM type select box change event
    const llmTypeSelect = document.getElementById('ai_helper_model_profile_llm_type');

    function isBaseUriRequired(selectValue) {
      if (selectValue == '<%= RedmineAiHelper::LlmProvider::LLM_OPENAI_COMPATIBLE %>' ||
          selectValue == '<%= RedmineAiHelper::LlmProvider::LLM_AZURE_OPENAI %>') {
        return true;
      }
      return false; // Base URI is not required for other LLM types
    }

    function handleLlmTypeChange() {
      const selectedValue = llmTypeSelect.value;
      const baseUriElement = document.getElementById('ai-helper-model-base-uri');
      const accessKeyRequiredElement = document.querySelector('#ai-helper-mode-access-key .required');
      const organizationIdElement = document.getElementById('ai-helper-model-organization-id');

      if (isBaseUriRequired(selectedValue) == true) {
        if (baseUriElement) baseUriElement.style.display = 'block';
      } else {
        if (baseUriElement) baseUriElement.style.display = 'none';
      }

      if (selectedValue == '<%= RedmineAiHelper::LlmProvider::LLM_OPENAI_COMPATIBLE %>') {
        if (accessKeyRequiredElement) accessKeyRequiredElement.style.display = 'none';
      } else {
        if (accessKeyRequiredElement) accessKeyRequiredElement.style.display = 'block';
      }

      if (selectedValue == '<%= RedmineAiHelper::LlmProvider::LLM_OPENAI %>') {
        if (organizationIdElement) organizationIdElement.style.display = 'block';
      } else {
        if (organizationIdElement) organizationIdElement.style.display = 'none';
      }
    }

    if (llmTypeSelect) {
      llmTypeSelect.addEventListener('change', handleLlmTypeChange);

      // Trigger change event on page load
      handleLlmTypeChange();
    }
  });
</script>

redmine-n8n/redmine/plugins/redmine_ai_helper/app/views/ai_helper_model_profiles/_show.html.erb
<hr/>
<div class="contextual">
    <%= link_to(sprite_icon('edit', l(:button_edit)), ai_helper_model_profiles_edit_path(@model_profile), :class => 'icon icon-edit') %>

    <%= link_to(sprite_icon('del', l(:button_delete)), ai_helper_model_profiles_destroy_url(id: @model_profile), method: :delete, data: { confirm: l('ai_helper.model_profiles.messages.confirm_delete') }, :class => 'icon icon-del') %>

</div>
<p>
  <%= label_tag AiHelperModelProfile.human_attribute_name(:llm_type) %>
  <%= @model_profile.display_llm_type %>
</p>
<p>
  <%= label_tag AiHelperModelProfile.human_attribute_name(:access_key) %>
  <%= @model_profile.masked_access_key %>
</p>
<p>
  <%= label_tag AiHelperModelProfile.human_attribute_name(:llm_model) %>
  <%= @model_profile.llm_model %>
</p>
<p>
  <%= label_tag AiHelperModelProfile.human_attribute_name(:temperature) %>
  <%= @model_profile.temperature %>
</p>
<p>
  <%= label_tag AiHelperModelProfile.human_attribute_name(:max_tokens) %>
  <%= @model_profile.max_tokens %>
</p>
<% if@model_profile.llm_type == RedmineAiHelper::LlmProvider::LLM_OPENAI %>
<p>
  <%= label_tag AiHelperModelProfile.human_attribute_name(:organization_id) %>
  <%= @model_profile.organization_id %>
</p>
<% end %>
<% if @model_profile.base_uri_required? %>
<p>
  <%= label_tag AiHelperModelProfile.human_attribute_name(:base_uri) %>
  <% unless @model_profile.base_uri.blank? %>
    <%= link_to @model_profile.base_uri, @model_profile.base_uri %>
  <% end %>
</p>
<% end %>
<div id="ai_helper_model_type" style="display: none;"><%= @model_profile.llm_type %></div>

redmine-n8n/redmine/plugins/redmine_ai_helper/app/views/ai_helper_model_profiles/edit.html.erb
<% html_title l('ai_helper.model_profiles.edit_profile_title')%>
<h2><%= l('ai_helper.model_profiles.edit_profile_title') %></h2>
<%= labelled_form_for @model_profile, url: ai_helper_model_profiles_update_path(id: @model_profile), method: :post, html: {autocomplete: "off"} do |f| %>
 <%= render partial: "form", locals: {f: f} %>

<%= f.submit t(:button_submit) %>
<%= link_to l(:button_cancel), ai_helper_setting_path %>
<% end %>

redmine-n8n/redmine/plugins/redmine_ai_helper/app/views/ai_helper_model_profiles/new.html.erb
<% html_title l('ai_helper.model_profiles.create_profile_title')%>
<h2><%= l('ai_helper.model_profiles.create_profile_title') %></h2>
<%= labelled_form_for @model_profile, html: {autocomplete: "off"} do |f| %>
  <%= render partial: "form", locals: {f: f} %>
  <%= f.submit t(:button_submit) %>
  <%= link_to l(:button_cancel), ai_helper_setting_path %>
<% end %>