redmine-n8n/redmine/plugins/redmine_ai_helper/config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html
RedmineApp::Application.routes.draw do
  post "projects/:id/ai_helper/chat", to: "ai_helper#chat", as: "ai_helper_chat"
  get "projects/:id/ai_helper/chat_form", to: "ai_helper#chat_form", as: "ai_helper_chat_form"
  get "projects/:id/ai_helper/reload", to: "ai_helper#reload", as: "ai_helper_reload"
  get "projects/:id/ai_helper/clear", to: "ai_helper#clear", as: "ai_helper_clear"
  get "projects/:id/ai_helper/history", to: "ai_helper#history", as: "ai_helper_history"
  get "projects/:id/ai_helper/conversation/:conversation_id", to: "ai_helper#conversation", as: "ai_helper_conversation"
  delete "projects/:id/ai_helper/conversation/:conversation_id", to: "ai_helper#conversation", as: "ai_helper_delete_conversation"
  post "projects/:id/ai_helper/call_llm", to: "ai_helper#call_llm", as: "ai_helper_call_llm"
  get "ai_helper/issue/:id/summary", to: "ai_helper#issue_summary", as: "ai_helper_issue_summary"
  post "ai_helper/issue/:id/generate_summary", to: "ai_helper#generate_issue_summary", as: "ai_helper_generate_issue_summary"
  get "ai_helper/wiki/:id/summary", to: "ai_helper#wiki_summary", as: "ai_helper_wiki_summary"
  post "ai_helper/wiki/:id/generate_summary", to: "ai_helper#generate_wiki_summary", as: "ai_helper_generate_wiki_summary"
  post "ai_helper/issue/:id/generate_reply", to: "ai_helper#generate_issue_reply", as: "ai_helper_generate_issue_reply"
  post "ai_helper/issue/:id/subissue_gen", to: "ai_helper#generate_sub_issues", as: "ai_helper_subissue_gen"
  post "ai_helper/issue/:id/add_sub_issues", to: "ai_helper#add_sub_issues", as: "ai_helper_add_sub_issues"
  get "ai_helper/issue/:id/similar_issues", to: "ai_helper#similar_issues", as: "ai_helper_similar_issues"
  get "projects/:id/ai_helper/project_health", to: "ai_helper#project_health", as: "ai_helper_project_health"
  get "projects/:id/ai_helper/generate_project_health", to: "ai_helper#generate_project_health", as: "ai_helper_generate_project_health"
  post "projects/:id/ai_helper/project_health_pdf", to: "ai_helper#project_health_pdf", as: "ai_helper_project_health_pdf"
  post "projects/:id/ai_helper/project_health_markdown", to: "ai_helper#project_health_markdown", as: "ai_helper_project_health_markdown"

  get "ai_helper_settings/index", to: "ai_helper_settings#index", as: "ai_helper_setting"
  post "ai_helper_settings/index", to: "ai_helper_settings#update", as: "ai_helper_setting_update"

  get "ai_helper_model_profiles", to: "ai_helper_model_profiles#index", as: "ai_helper_model_profiles"
  get "ai_helper_model_profiles/:id", to: "ai_helper_model_profiles#show", as: "ai_helper_model_profiles_show"
  get "ai_helper_model_profiles/:id/edit", to: "ai_helper_model_profiles#edit", as: "ai_helper_model_profiles_edit"
  get "ai_helper_model_profiles_new", to: "ai_helper_model_profiles#new", as: "ai_helper_model_profiles_new"
  post "ai_helper_model_profiles", to: "ai_helper_model_profiles#create", as: "ai_helper_model_profiles_create"
  post "ai_helper_model_profiles/:id/edit", to: "ai_helper_model_profiles#update", as: "ai_helper_model_profiles_update"
  delete "ai_helper_model_profiles/:id", to: "ai_helper_model_profiles#destroy", as: "ai_helper_model_profiles_destroy"

  # get "ai_helper_project_settings/:id", to: "ai_helper_project_settings#show", as: "ai_helper_project_settings"
  patch "projects/:id/ai_helper_project_settings", to: "ai_helper_project_settings#update", as: "ai_helper_project_settings_update"
end

redmine-n8n/redmine/plugins/redmine_ai_helper/app/models/ai_helper_setting.rb
# frozen_string_literal: true
#
# AiHelperSetting model for storing settings related to AI helper
class AiHelperSetting < ApplicationRecord
  include Redmine::SafeAttributes
  belongs_to :model_profile, class_name: "AiHelperModelProfile"
  validates :vector_search_uri, :presence => true, if: :vector_search_enabled?
  validates :vector_search_uri, :format => { with: URI::regexp(%w[http https]), message: l("ai_helper.model_profiles.messages.must_be_valid_url") }, if: :vector_search_enabled?

  safe_attributes "model_profile_id", "additional_instructions", "version", "vector_search_enabled", "vector_search_uri", "vector_search_api_key", "embedding_model", "dimension", "vector_search_index_name", "vector_search_index_type", "embedding_url"

  class << self
    # This method is used to find or create an AiHelperSetting record.
    # It first tries to find the first record in the AiHelperSetting table.
    def find_or_create
      data = AiHelperSetting.order(:id).first
      data || AiHelperSetting.create!
    end

    def setting
      find_or_create
    end

    def vector_search_enabled?
      setting.vector_search_enabled
    end
  end

  # returns true if embedding_url is required.
  def embedding_url_enabled?
    model_profile&.llm_type == RedmineAiHelper::LlmProvider::LLM_AZURE_OPENAI
  end

  def max_tokens
    return nil unless model_profile&.max_tokens
    return nil if model_profile.max_tokens <= 0
    model_profile.max_tokens
  end
end

redmine-n8n/redmine/plugins/redmine_ai_helper/app/controllers/ai_helper_settings_controller.rb
# frozen_string_literal: true
# AiHelperSetting Controller for managing AI Helper settings
class AiHelperSettingsController < ApplicationController
  layout "admin"
  before_action :require_admin, :find_setting
  self.main_menu = false

  # Display the settings page
  def index
  end

  # Update the settings
  def update
    @setting.safe_attributes = params[:ai_helper_setting]
    if @setting.save
      flash[:notice] = l(:notice_successful_update)
      redirect_to action: :index
    else
      render action: :index
    end
  end

  private

  # Find or create the AI Helper setting and load model profiles
  def find_setting
    @setting = AiHelperSetting.find_or_create
    @model_profiles = AiHelperModelProfile.order(:name)
  end
end

redmine-n8n/redmine/plugins/redmine_ai_helper/app/helpers/ai_helper_settings_helper.rb
module AiHelperSettingsHelper
end

redmine-n8n/redmine/plugins/redmine_ai_helper/app/views/ai_helper_settings/index.html.erb
<h2><%= t(:label_ai_helper) %></h2>

<%= labelled_form_for @setting, url: ai_helper_setting_update_url, method: :post do |f| %>
<%= error_messages_for "setting" %>
<div class="box tabular">
    <p>
        <%
            options = @model_profiles.map{|p| [p.display_name, p.id]}
        %>
        <%= f.select :model_profile_id, options, include_blank: true, required: true %>
        <%= link_to ai_helper_model_profiles_new_url do %>
            <%= sprite_icon('add') %>
            <%= t(:label_new) %>
        <% end %>
    </p>
        <div id="ai_helper_model_profile_description">
        </div>

    <hr>
    <p>
        <%= f.check_box :vector_search_enabled %>
    </p>
    <div id="ai-helper-vector-search">
        <p>
            <%= f.text_field :vector_search_uri, size: 60, required: true %>
        </p>
        <p>
            <%= f.text_field :vector_search_api_key, size: 60 %>
        </p>
        <p>
            <%= f.text_field :embedding_model, size: 60 %>
        </p>
        <p id="ai_helper_dimension" style="display: none;">
            <%= f.text_field :dimension, size: 60 %>
        </p>
        <p id="ai_helper_embedding_url" style="display: none;">
            <%= f.text_field :embedding_url, size: 90 %>
        </p>
    </div>
    <hr>
    <p><%= f.text_area :additional_instructions, rows: 12 %></p>
</div>
<%= f.submit t(:button_submit) %>
<% end %>

<script>
    function loadModelProfile(id) {
        $.ajax({
            url: '<%= ai_helper_model_profiles_path%>/' + id,
            type: 'GET',
            success: function(data) {
                $('#ai_helper_model_profile_description').html(data);
                modelTypeChanged();
            },
            error: function() {
                $('#ai_helper_model_profile_description').html('error');
            }
        });
    }

    function setModelProfile() {
        var selectedId = $('#ai_helper_setting_model_profile_id').val();
        if (selectedId) {
            loadModelProfile(selectedId);

        } else {
            $('#ai_helper_model_profile_description').html('');
        }
    }

    function setVectorSearchVisible() {
        var vectorSearchEnabled = $('#ai_helper_setting_vector_search_enabled').is(':checked');
        if (vectorSearchEnabled) {
            $('#ai-helper-vector-search').show();
        } else {
            $('#ai-helper-vector-search').hide();
        }
    }

    function modelTypeChanged() {
        var modelType = $('#ai_helper_model_type').text();
        if (modelType === '<%= RedmineAiHelper::LlmProvider::LLM_OPENAI_COMPATIBLE %>') {
            $('#ai_helper_dimension').show();
        } else {
            $('#ai_helper_dimension').hide();
        }
        if (modelType === '<%= RedmineAiHelper::LlmProvider::LLM_AZURE_OPENAI %>') {
            $('#ai_helper_embedding_url').show();
        } else {
            $('#ai_helper_embedding_url').hide();
        }
    }


    $(document).ready(function() {
        $('#ai_helper_setting_model_profile_id').change(function() {
            setModelProfile();
        });
        $('#ai_helper_setting_vector_search_enabled').change(function() {
            setVectorSearchVisible();
        });
    });
    setModelProfile();
    setVectorSearchVisible();
</script>